 # Lab 1

**Adam Aiken**

February 9th, 2026

I will go through the lab below, using a mix of Python and Markdown. Experiment with Markdown in these labs. Try making things **bold**. Or *italics*. Try adding a [URL link](https://aaiken1.github.io).

## Part 3

I like to have new Markdown chunks for each question. I'm using `##` for my sub-headers.

In [1]:
formula_string = 'Capital Asset Pricing Model'
print(formula_string)

Capital Asset Pricing Model


In [2]:
type(formula_string)

str

## Part 4

An even better way might be to define each piece of the formula. So, `FV = 100`, etc. But, I wanted to show you that you can use Python like a formula. 

Don't try guessing - there's no way to know that `**` means exponent, unless you've coded before.

In [3]:
pv = 100/(1+0.05)**2
type(pv)

float

In [4]:
print("Present Value: $%.2f" % pv)

Present Value: $90.70


## Part 5

Lists are very useful and come up a lot. Notice how you can mix types inside the list. 

In [5]:
stock = ["Apple Inc.", "AAPL", 172.39]
type(stock)
print(stock[1])

AAPL


This works too to get an item out.

In [6]:
stock[1]

'AAPL'

To save the item, I'd need to use an `=` and define a new variable.

In [7]:
s = stock[1]
s

'AAPL'

## Part 6

Watch your syntax with control structures. You need the `:`. And the correct indentation. Again, don't try to guess! Computers are literal. They aren't going to guess what you mean.

In [8]:
StockPercentile = 90

if StockPercentile >= 90:
    print('Add stock to buy list.')

Add stock to buy list.


In [9]:
StockPercentile = 80

if StockPercentile >= 90:
    print('Add stock to buy list.')
else: 
    print('Exclude stock.')

Exclude stock.


For this question, note that the order the statements matters, depending on how you wrote your `if`, `elif`, and `else`. If you have `StockPercentile >= 90`, you'll get a `true` and exit.

In [10]:
StockPercentile = 110

if StockPercentile > 100:
    print('Check calculations.')
elif StockPercentile >= 90:
    print('Add stock to buy list.')
else: 
    print('Exclude stock.')

Check calculations.


You could also write the statements like this so that the order does not matter.

In [11]:
StockPercentile = 110

if StockPercentile > 100:
    print('Check calculations.')
elif 90 <= StockPercentile <= 100:
    print('Add stock to buy list.')
else: 
    print('Exclude stock.')

Check calculations.


## Part 7

In [12]:
i = 10

while i >= 1:
    print('Counting down... %d' % i)
    i -= 1
print('Blastoff!')

Counting down... 10
Counting down... 9
Counting down... 8
Counting down... 7
Counting down... 6
Counting down... 5
Counting down... 4
Counting down... 3
Counting down... 2
Counting down... 1
Blastoff!


## Part 8

This is where we bring in `numpy`. I'm doing my `import` statement here. Normally, we put these up at the top of our code. We'll have many different bits of "starter" code as we go. 

Make sure you can follow the logic of indexing. Selecting items out of arrays, lists, and data frames is part of the day-to-day coding when dealing with data. 

In [13]:
import numpy as np

a = np.arange(5, 105, 5)
a

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

In [14]:
print(a[0])
print(a[9])

5
50


In [15]:
b = a ** 2
b
type(b)

numpy.ndarray

In [16]:
c = np.eye(4)
c

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
c * 3

array([[3., 0., 0., 0.],
       [0., 3., 0., 0.],
       [0., 0., 3., 0.],
       [0., 0., 0., 3.]])

In [18]:
print(c[1,1])

1.0


In [19]:
print(c[:,1])

[0. 1. 0. 0.]


In [20]:
print(c[:,:2])

[[1. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]]


In [21]:
print(c[0:2,1:3])

[[0. 0.]
 [1. 0.]]


Note that this pattern appears twice, so you can get two ways!


## Part 9

$\LaTeX$ is how we write math in technical writing. Notice all of the dollar signs - this tells Markdown where the $\LaTeX$ begins and ends.

Once you know a few $\LaTeX$ ideas, I think using LLMs to write your math for you is the way to go. You'll get what you want, or something very close. Then, you can edit. 

People who write a lot of math have strong opinions about the correct formatting. We don't have to worry about that here.

$$R_i = R_f + \beta_i (R_m - R_f)$$

$$
Q = \frac{1}{1 + \exp\left(-a - \sum_{j=1}^{m} b_j X_j\right)} \tag{1}
$$ 


You can also have $\LaTeX$ expressions in a line of text, like this: $Q = \frac{1}{1 + \exp\left(-a - \sum_{j=1}^{m} b_j X_j\right)}$

This works too. I'm basically having a conversation with ChatGPT 4o about $\LaTeX$ and Markdown and trying different things. When I write papers, I just use $\LaTeX$ - it's not just for math, it's a way to typeset and entire paper, book, etc.

\begin{equation}
Q = \frac{1}{1 + \exp\left(-a - \sum_{j=1}^{m} b_j X_j\right)}
\end{equation}