# Lab 1

**Adam Aiken**

February 6th, 2022

In [3]:
formula_string = 'Capital Asset Pricing Model'
print(formula_string)

Capital Asset Pricing Model


In [10]:
pv = 100/(1+0.05)**2
type(pv)

float

In [9]:
print("Present Value: $%.2f" % pv)

Present Value: $90.70


In [6]:
stock = ["Apple Inc.", "AAPL", 172.39]
type(stock)
print(stock[1])

AAPL


In [2]:
StockPercentile = 90

if StockPercentile >= 90:
    print('Add stock to buy list.')

Add stock to buy list.


In [3]:
StockPercentile = 80

if StockPercentile >= 90:
    print('Add stock to buy list.')
else: 
    print('Exclude stock.')

Exclude stock.


In [4]:
StockPercentile = 110

if StockPercentile > 100:
    print('Check calculations.')
elif StockPercentile >= 90:
    print('Add stock to buy list.')
else: 
    print('Exclude stock.')

Check calculations.


In [5]:
i = 10

while i >= 1:
    print('Counting down... %d' % i)
    i -= 1
print('Blastoff!')

Counting down... 10
Counting down... 9
Counting down... 8
Counting down... 7
Counting down... 6
Counting down... 5
Counting down... 4
Counting down... 3
Counting down... 2
Counting down... 1
Blastoff!


In [8]:
import numpy as np

a = np.arange(5, 105, 5)
a

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

In [10]:
print(a[0])
print(a[9])

5
50


In [12]:
b = a ** 2
b
type(b)

numpy.ndarray

In [13]:
c = np.eye(4)
c

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
c * 3

array([[3., 0., 0., 0.],
       [0., 3., 0., 0.],
       [0., 0., 3., 0.],
       [0., 0., 0., 3.]])

In [15]:
print(c[1,1])

1.0


In [33]:
print(c[:,1])

[0. 1. 0. 0.]


In [38]:
print(c[:,:2])

[[1. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]]


In [41]:
print(c[0:2,1:3])

[[0. 0.]
 [1. 0.]]
